"""Centralized Korean company-name overrides for mobile API payloads."""

from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Any

KR_COMPANY_NAMES: dict[str, str] = {
    '000270': '기아',
    '000660': 'SK하이닉스',
    '000810': '삼성화재',
    '003670': '포스코퓨처엠',
    '005380': '현대차',
    '005490': 'POSCO홀딩스',
    '005830': 'DB손해보험',
    '005930': '삼성전자',
    '006400': '삼성SDI',
    '009150': '삼성전기',
    '010130': '고려아연',
    '010140': '삼성중공업',
    '012330': '현대모비스',
    '015760': '한국전력',
    '017670': 'SK텔레콤',
    '028260': '삼성물산',
    '030200': 'KT',
    '032820': '우리기술',
    '032830': '삼성생명',
    '034020': '두산에너빌리티',
    '034730': 'SK',
    '035420': 'NAVER',
    '035720': '카카오',
    '051600': '한전KPS',
    '051910': 'LG화학',
    '052690': '한전기술',
    '055550': '신한지주',
    '066570': 'LG전자',
    '068270': '셀트리온',
    '083650': '비에이치아이',
    '086790': '하나금융지주',
    '094820': '일진파워',
    '096770': 'SK이노베이션',
    '105560': 'KB금융',
    '105840': '우진',
    '207940': '삼성바이오로직스',
    '316140': '우리금융지주',
    '329180': 'HD현대중공업',
    '373220': 'LG에너지솔루션',
}

US_COMPANY_NAMES_KO: dict[str, str] = {
    'AAPL': '애플',
    'ABBV': '애브비',
    'ABNB': '에어비앤비',
    'ABT': '애보트 래버러토리스',
    'ADBE': '어도비',
    'ADI': '아날로그 디바이시스',
    'AEP': '아메리칸 일렉트릭 파워',
    'AFL': '애플랙',
    'AI': '씨쓰리에이아이',
    'AIG': '에이아이지',
    'AIZ': '어슈런트',
    'ALB': '앨버말',
    'AMAT': '어플라이드 머티어리얼즈',
    'AMD': '에이엠디',
    'AMGN': '암젠',
    'AMT': '아메리칸 타워',
    'AMZN': '아마존',
    'ANET': '아리스타 네트웍스',
    'APA': '에이피에이',
    'APH': '암페놀',
    'APTV': '앱티브',
    'ARM': '암 홀딩스',
    'ASML': '에이에스엠엘',
    'AVGO': '브로드컴',
    'AXP': '아메리칸 익스프레스',
    'BA': '보잉',
    'BABA': '알리바바',
    'BAC': '뱅크오브아메리카',
    'BEN': '프랭클린 리소시스',
    'BEP': '브룩필드 리뉴어블',
    'BHP': '비에이치피',
    'BIIB': '바이오젠',
    'BKNG': '부킹홀딩스',
    'BKTI': '비케이 테크놀로지스',
    'BLK': '블랙록',
    'BMY': '브리스톨 마이어스 스큅',
    'BRK-B': '버크셔 해서웨이',
    'BSX': '보스턴 사이언티픽',
    'BWA': '보그워너',
    'BWXT': '비더블유엑스 테크놀로지스',
    'BX': '블랙스톤',
    'BZAI': '블레이즈',
    'C': '씨티그룹',
    'CARR': '캐리어 글로벌',
    'CAT': '캐터필러',
    'CB': '처브',
    'CCJ': '카메코',
    'CCL': '카니발',
    'CDNL': '카디널 인프라스트럭처',
    'CEG': '컨스텔레이션 에너지',
    'CF': '씨에프 인더스트리즈',
    'CHTR': '차터 커뮤니케이션즈',
    'CI': '시그나',
    'CIEN': '시에나',
    'CMCL': '칼레도니아 마이닝',
    'CMCSA': '컴캐스트',
    'CNC': '센틴',
    'COF': '캐피털 원',
    'COHR': '코히런트',
    'COIN': '코인베이스',
    'COP': '코노코필립스',
    'COST': '코스트코',
    'CPNG': '쿠팡',
    'CPRT': '코파트',
    'CPT': '캠든 프로퍼티 트러스트',
    'CRM': '세일즈포스',
    'CRMD': '코메딕스',
    'CRWD': '크라우드스트라이크',
    'CSCO': '시스코',
    'CSX': '씨에스엑스',
    'CURI': '큐리오시티스트림',
    'CVS': '씨브이에스 헬스',
    'CVX': '셰브론',
    'CXDO': '크레센도',
    'CYBR': '사이버아크',
    'DAL': '델타항공',
    'DCTH': '델캐스 시스템스',
    'DD': '듀폰',
    'DDOG': '데이터독',
    'DE': '디어',
    'DECK': '데커스',
    'DELL': '델 테크놀로지스',
    'DHR': '다나허',
    'DIS': '디즈니',
    'DLR': '디지털 리얼티',
    'DNN': '데니슨 마인스',
    'DOC': '헬스피크 프로퍼티스',
    'DOW': '다우',
    'DUK': '듀크 에너지',
    'DVA': '다비타',
    'DVN': '데번 에너지',
    'EA': '일렉트로닉 아츠',
    'EBAY': '이베이',
    'EL': '에스티 로더',
    'ELA': '엔벨라',
    'ELV': '엘리번스 헬스',
    'EME': '엠코어',
    'ENPH': '엔페이즈 에너지',
    'EOG': '이오지 리소시스',
    'EPSN': '엡실론 에너지',
    'EQIX': '에퀴닉스',
    'ESS': '에섹스 프로퍼티 트러스트',
    'ETN': '이튼',
    'EW': '에드워즈 라이프사이언시스',
    'EXC': '엑셀론',
    'EXPD': '익스피다이터스',
    'F': '포드',
    'FCX': '프리포트 맥모란',
    'FDX': '페덱스',
    'FIX': '컴포트 시스템즈',
    'FOX': '폭스',
    'FRT': '페더럴 리얼티 인베스트먼트 트러스트',
    'FSLR': '퍼스트솔라',
    'FTNT': '포티넷',
    'GAMB': '갬블링닷컴',
    'GD': '제너럴 다이내믹스',
    'GE': '지이 에어로스페이스',
    'GEV': '지이 버노바',
    'GFS': '글로벌파운드리스',
    'GILD': '길리어드 사이언스',
    'GL': '글로브 라이프',
    'GM': '제너럴모터스',
    'GNRC': '제네락',
    'GOOG': '알파벳',
    'GOOGL': '알파벳',
    'GRMN': '가민',
    'GS': '골드만삭스',
    'GST': '지에스티',
    'HAL': '핼리버튼',
    'HAS': '해즈브로',
    'HD': '홈디포',
    'HIG': '하트퍼드',
    'HII': '헌팅턴 잉걸스',
    'HLT': '힐튼',
    'HON': '하니웰',
    'HPE': '휴렛팩커드 엔터프라이즈',
    'HST': '호스트 호텔',
    'HUM': '휴매나',
    'HWM': '하우멧 에어로스페이스',
    'IBKR': '인터랙티브 브로커스',
    'IBM': '아이비엠',
    'IDR': '아이다호 스트래티직 리소시스',
    'IFF': '인터내셔널 플레이버스 앤 프래그런스',
    'INCY': '인사이트',
    'INTC': '인텔',
    'INTU': '인튜이트',
    'ISRG': '인튜이티브 서지컬',
    'IVZ': '인베스코',
    'JBL': '자빌',
    'JCI': '존슨콘트롤즈',
    'JNJ': '존슨앤드존슨',
    'JPM': '제이피모건 체이스',
    'KEYS': '키사이트',
    'KKR': '케이케이알',
    'KLAC': '케이엘에이',
    'KMB': '킴벌리클라크',
    'KO': '코카콜라',
    'LCID': '루시드',
    'LEU': '센트러스 에너지',
    'LITE': '루멘텀',
    'LLY': '일라이 릴리',
    'LMT': '록히드마틴',
    'LOW': '로우스',
    'LRCX': '램리서치',
    'LSCC': '래티스 세미컨덕터',
    'LYB': '라이온델바젤',
    'MA': '마스터카드',
    'MAMA': '마마스 크리에이션스',
    'MAR': '메리어트 인터내셔널',
    'MCD': '맥도날드',
    'MCHP': '마이크로칩 테크놀로지',
    'MDB': '몽고디비',
    'MDLZ': '몬델리즈',
    'MDT': '메드트로닉',
    'MELI': '메르카도리브레',
    'MET': '메트라이프',
    'META': '메타',
    'MGA': '마그나',
    'MLM': '마틴 마리에타 머티리얼즈',
    'MO': '알트리아',
    'MPWR': '모놀리식 파워 시스템즈',
    'MRK': '머크',
    'MRNA': '모더나',
    'MRVL': '마벨 테크놀로지',
    'MS': '모건스탠리',
    'MSFT': '마이크로소프트',
    'MU': '마이크론',
    'NCLH': '노르웨이지안 크루즈',
    'NDAQ': '나스닥',
    'NDSN': '노드슨',
    'NEE': '넥스트에라 에너지',
    'NEM': '뉴몬트',
    'NET': '클라우드플레어',
    'NFLX': '넷플릭스',
    'NKE': '나이키',
    'NNE': '나노 뉴클리어 에너지',
    'NOC': '노스럽 그러먼',
    'NOW': '서비스나우',
    'NSC': '노퍽 서던',
    'NTRS': '노던 트러스트',
    'NUE': '뉴코어',
    'NVDA': '엔비디아',
    'NVO': '노보 노디스크',
    'NXE': '넥스젠 에너지',
    'NXPI': '엔엑스피 세미컨덕터스',
    'O': '리얼티 인컴',
    'OKLO': '오클로',
    'OKTA': '옥타',
    'ON': '온 세미컨덕터',
    'ONTO': '온투 이노베이션',
    'ORCL': '오라클',
    'OXY': '옥시덴털 페트롤리엄',
    'PANW': '팔로알토 네트웍스',
    'PARA': '파라마운트',
    'PATH': '유아이패스',
    'PAYS': '페이사인',
    'PCRFY': '파나소닉 홀딩스',
    'PEG': '퍼블릭 서비스 엔터프라이즈 그룹',
    'PEP': '펩시코',
    'PFE': '화이자',
    'PFG': '프린시플 파이낸셜',
    'PG': '피앤지',
    'PLD': '프로로지스',
    'PLTR': '팔란티어',
    'PM': '필립모리스',
    'PNC': '피엔씨 파이낸셜',
    'PRU': '프루덴셜 파이낸셜',
    'PSA': '퍼블릭 스토리지',
    'PTC': '피티씨',
    'PWR': '퀀타 서비스',
    'PYPL': '페이팔',
    'QCOM': '퀄컴',
    'QS': '퀀텀스케이프',
    'RBLX': '로블록스',
    'RDDT': '레딧',
    'REGN': '리제네론',
    'RHLD': '리졸루트 홀딩스',
    'RIGL': '라이젤 파마슈티컬스',
    'RIO': '리오 틴토',
    'RIVN': '리비안',
    'RL': '랄프 로렌',
    'ROK': '록웰 오토메이션',
    'ROKU': '로쿠',
    'ROST': '로스스토어스',
    'RTX': '알티엑스',
    'S': '센티넬원',
    'SBUX': '스타벅스',
    'SCCO': '서던 코퍼',
    'SCHW': '찰스 슈왑',
    'SEDG': '솔라엣지',
    'SHOP': '쇼피파이',
    'SLB': '에스엘비',
    'SLP': '시뮬레이션스 플러스',
    'SMCI': '슈퍼마이크로컴퓨터',
    'SMR': '뉴스케일 파워',
    'SMTI': '사나라 메드테크',
    'SNDK': '샌디스크',
    'SNOW': '스노우플레이크',
    'SO': '서던 컴퍼니',
    'SPG': '사이먼 프로퍼티 그룹',
    'SPGI': '에스앤피 글로벌',
    'SQ': '블록',
    'SQM': '에스큐엠',
    'STLD': '스틸 다이내믹스',
    'STX': '시게이트',
    'SYK': '스트라이커',
    'T': '에이티앤티',
    'TEAM': '아틀라시안',
    'TEL': '티이 커넥티비티',
    'TER': '테라다인',
    'TGT': '타깃',
    'TJX': '티제이엑스',
    'TLS': '텔로스',
    'TM': '토요타',
    'TMO': '써모 피셔 사이언티픽',
    'TMUS': '티모바일 유에스',
    'TRV': '트래블러스',
    'TSEM': '타워 세미컨덕터',
    'TSLA': '테슬라',
    'TSM': '티에스엠씨',
    'TT': '트레인 테크놀로지스',
    'TTWO': '테이크투 인터랙티브',
    'TXN': '텍사스 인스트루먼트',
    'UAL': '유나이티드항공',
    'UBER': '우버',
    'UMC': '유나이티드 마이크로일렉트로닉스',
    'UNH': '유나이티드헬스 그룹',
    'UNP': '유니언 퍼시픽',
    'UPS': '유피에스',
    'URI': '유나이티드 렌털스',
    'USB': '유에스 뱅코프',
    'UUUU': '에너지 퓨얼스',
    'V': '비자',
    'VLO': '발레로 에너지',
    'VMC': '벌컨 머티리얼즈',
    'VMD': '비메드 헬스케어',
    'VRT': '버티브',
    'VST': '비스트라',
    'VTRS': '비아트리스',
    'VZ': '버라이즌',
    'WAT': '워터스',
    'WBD': '워너브러더스 디스커버리',
    'WDAY': '워크데이',
    'WDC': '웨스턴디지털',
    'WFC': '웰스파고',
    'WMT': '월마트',
    'WSM': '윌리엄스소노마',
    'WST': '웨스트 파마슈티컬',
    'XOM': '엑슨모빌',
    'ZBRA': '지브라 테크놀로지스',
    'ZS': '지스케일러',
}

DISPLAY_OVERRIDES: dict[str, str] = {
    '000270': '기아',
    '000660': 'SK하이닉스',
    '000810': '삼성화재',
    '003670': '포스코퓨처엠',
    '005380': '현대차',
    '005490': 'POSCO홀딩스',
    '005830': 'DB손해보험',
    '005930': '삼성전자',
    '006400': '삼성SDI',
    '009150': '삼성전기',
    '010130': '고려아연',
    '010140': '삼성중공업',
    '012330': '현대모비스',
    '015760': '한국전력',
    '017670': 'SK텔레콤',
    '028260': '삼성물산',
    '030200': 'KT',
    '032820': '우리기술',
    '032830': '삼성생명',
    '034020': '두산에너빌리티',
    '034730': 'SK',
    '035420': 'NAVER',
    '035720': '카카오',
    '051600': '한전KPS',
    '051910': 'LG화학',
    '052690': '한전기술',
    '055550': '신한지주',
    '066570': 'LG전자',
    '068270': '셀트리온',
    '083650': '비에이치아이',
    '086790': '하나금융지주',
    '094820': '일진파워',
    '096770': 'SK이노베이션',
    '105560': 'KB금융',
    '105840': '우진',
    '207940': '삼성바이오로직스',
    '316140': '우리금융지주',
    '329180': 'HD현대중공업',
    '373220': 'LG에너지솔루션',
    'AAPL': '애플',
    'ABBV': '애브비',
    'ABNB': '에어비앤비',
    'ABT': '애보트 래버러토리스',
    'ADBE': '어도비',
    'ADI': '아날로그 디바이시스',
    'AEP': '아메리칸 일렉트릭 파워',
    'AFL': '애플랙',
    'AI': '씨쓰리에이아이',
    'AIG': '에이아이지',
    'AIZ': '어슈런트',
    'ALB': '앨버말',
    'AMAT': '어플라이드 머티어리얼즈',
    'AMD': '에이엠디',
    'AMGN': '암젠',
    'AMT': '아메리칸 타워',
    'AMZN': '아마존',
    'ANET': '아리스타 네트웍스',
    'APA': '에이피에이',
    'APH': '암페놀',
    'APTV': '앱티브',
    'ARM': '암 홀딩스',
    'ASML': '에이에스엠엘',
    'AVGO': '브로드컴',
    'AXP': '아메리칸 익스프레스',
    'BA': '보잉',
    'BABA': '알리바바',
    'BAC': '뱅크오브아메리카',
    'BEN': '프랭클린 리소시스',
    'BEP': '브룩필드 리뉴어블',
    'BHP': '비에이치피',
    'BIIB': '바이오젠',
    'BKNG': '부킹홀딩스',
    'BKTI': '비케이 테크놀로지스',
    'BLK': '블랙록',
    'BMY': '브리스톨 마이어스 스큅',
    'BRK-B': '버크셔 해서웨이',
    'BSX': '보스턴 사이언티픽',
    'BWA': '보그워너',
    'BWXT': '비더블유엑스 테크놀로지스',
    'BX': '블랙스톤',
    'BZAI': '블레이즈',
    'C': '씨티그룹',
    'CARR': '캐리어 글로벌',
    'CAT': '캐터필러',
    'CB': '처브',
    'CCJ': '카메코',
    'CCL': '카니발',
    'CDNL': '카디널 인프라스트럭처',
    'CEG': '컨스텔레이션 에너지',
    'CF': '씨에프 인더스트리즈',
    'CHTR': '차터 커뮤니케이션즈',
    'CI': '시그나',
    'CIEN': '시에나',
    'CMCL': '칼레도니아 마이닝',
    'CMCSA': '컴캐스트',
    'CNC': '센틴',
    'COF': '캐피털 원',
    'COHR': '코히런트',
    'COIN': '코인베이스',
    'COP': '코노코필립스',
    'COST': '코스트코',
    'CPNG': '쿠팡',
    'CPRT': '코파트',
    'CPT': '캠든 프로퍼티 트러스트',
    'CRM': '세일즈포스',
    'CRMD': '코메딕스',
    'CRWD': '크라우드스트라이크',
    'CSCO': '시스코',
    'CSX': '씨에스엑스',
    'CURI': '큐리오시티스트림',
    'CVS': '씨브이에스 헬스',
    'CVX': '셰브론',
    'CXDO': '크레센도',
    'CYBR': '사이버아크',
    'DAL': '델타항공',
    'DCTH': '델캐스 시스템스',
    'DD': '듀폰',
    'DDOG': '데이터독',
    'DE': '디어',
    'DECK': '데커스',
    'DELL': '델 테크놀로지스',
    'DHR': '다나허',
    'DIS': '디즈니',
    'DLR': '디지털 리얼티',
    'DNN': '데니슨 마인스',
    'DOC': '헬스피크 프로퍼티스',
    'DOW': '다우',
    'DUK': '듀크 에너지',
    'DVA': '다비타',
    'DVN': '데번 에너지',
    'EA': '일렉트로닉 아츠',
    'EBAY': '이베이',
    'EL': '에스티 로더',
    'ELA': '엔벨라',
    'ELV': '엘리번스 헬스',
    'EME': '엠코어',
    'ENPH': '엔페이즈 에너지',
    'EOG': '이오지 리소시스',
    'EPSN': '엡실론 에너지',
    'EQIX': '에퀴닉스',
    'ESS': '에섹스 프로퍼티 트러스트',
    'ETN': '이튼',
    'EW': '에드워즈 라이프사이언시스',
    'EXC': '엑셀론',
    'EXPD': '익스피다이터스',
    'F': '포드',
    'FCX': '프리포트 맥모란',
    'FDX': '페덱스',
    'FIX': '컴포트 시스템즈',
    'FOX': '폭스',
    'FRT': '페더럴 리얼티 인베스트먼트 트러스트',
    'FSLR': '퍼스트솔라',
    'FTNT': '포티넷',
    'GAMB': '갬블링닷컴',
    'GD': '제너럴 다이내믹스',
    'GE': '지이 에어로스페이스',
    'GEV': '지이 버노바',
    'GFS': '글로벌파운드리스',
    'GILD': '길리어드 사이언스',
    'GL': '글로브 라이프',
    'GM': '제너럴모터스',
    'GNRC': '제네락',
    'GOOG': '알파벳',
    'GOOGL': '알파벳',
    'GRMN': '가민',
    'GS': '골드만삭스',
    'GST': '지에스티',
    'HAL': '핼리버튼',
    'HAS': '해즈브로',
    'HD': '홈디포',
    'HIG': '하트퍼드',
    'HII': '헌팅턴 잉걸스',
    'HLT': '힐튼',
    'HON': '하니웰',
    'HPE': '휴렛팩커드 엔터프라이즈',
    'HST': '호스트 호텔',
    'HUM': '휴매나',
    'HWM': '하우멧 에어로스페이스',
    'IBKR': '인터랙티브 브로커스',
    'IBM': '아이비엠',
    'IDR': '아이다호 스트래티직 리소시스',
    'IFF': '인터내셔널 플레이버스 앤 프래그런스',
    'INCY': '인사이트',
    'INTC': '인텔',
    'INTU': '인튜이트',
    'ISRG': '인튜이티브 서지컬',
    'IVZ': '인베스코',
    'JBL': '자빌',
    'JCI': '존슨콘트롤즈',
    'JNJ': '존슨앤드존슨',
    'JPM': '제이피모건 체이스',
    'KEYS': '키사이트',
    'KKR': '케이케이알',
    'KLAC': '케이엘에이',
    'KMB': '킴벌리클라크',
    'KO': '코카콜라',
    'LCID': '루시드',
    'LEU': '센트러스 에너지',
    'LITE': '루멘텀',
    'LLY': '일라이 릴리',
    'LMT': '록히드마틴',
    'LOW': '로우스',
    'LRCX': '램리서치',
    'LSCC': '래티스 세미컨덕터',
    'LYB': '라이온델바젤',
    'MA': '마스터카드',
    'MAMA': '마마스 크리에이션스',
    'MAR': '메리어트 인터내셔널',
    'MCD': '맥도날드',
    'MCHP': '마이크로칩 테크놀로지',
    'MDB': '몽고디비',
    'MDLZ': '몬델리즈',
    'MDT': '메드트로닉',
    'MELI': '메르카도리브레',
    'MET': '메트라이프',
    'META': '메타',
    'MGA': '마그나',
    'MLM': '마틴 마리에타 머티리얼즈',
    'MO': '알트리아',
    'MPWR': '모놀리식 파워 시스템즈',
    'MRK': '머크',
    'MRNA': '모더나',
    'MRVL': '마벨 테크놀로지',
    'MS': '모건스탠리',
    'MSFT': '마이크로소프트',
    'MU': '마이크론',
    'NCLH': '노르웨이지안 크루즈',
    'NDAQ': '나스닥',
    'NDSN': '노드슨',
    'NEE': '넥스트에라 에너지',
    'NEM': '뉴몬트',
    'NET': '클라우드플레어',
    'NFLX': '넷플릭스',
    'NKE': '나이키',
    'NNE': '나노 뉴클리어 에너지',
    'NOC': '노스럽 그러먼',
    'NOW': '서비스나우',
    'NSC': '노퍽 서던',
    'NTRS': '노던 트러스트',
    'NUE': '뉴코어',
    'NVDA': '엔비디아',
    'NVO': '노보 노디스크',
    'NXE': '넥스젠 에너지',
    'NXPI': '엔엑스피 세미컨덕터스',
    'O': '리얼티 인컴',
    'OKLO': '오클로',
    'OKTA': '옥타',
    'ON': '온 세미컨덕터',
    'ONTO': '온투 이노베이션',
    'ORCL': '오라클',
    'OXY': '옥시덴털 페트롤리엄',
    'PANW': '팔로알토 네트웍스',
    'PARA': '파라마운트',
    'PATH': '유아이패스',
    'PAYS': '페이사인',
    'PCRFY': '파나소닉 홀딩스',
    'PEG': '퍼블릭 서비스 엔터프라이즈 그룹',
    'PEP': '펩시코',
    'PFE': '화이자',
    'PFG': '프린시플 파이낸셜',
    'PG': '피앤지',
    'PLD': '프로로지스',
    'PLTR': '팔란티어',
    'PM': '필립모리스',
    'PNC': '피엔씨 파이낸셜',
    'PRU': '프루덴셜 파이낸셜',
    'PSA': '퍼블릭 스토리지',
    'PTC': '피티씨',
    'PWR': '퀀타 서비스',
    'PYPL': '페이팔',
    'QCOM': '퀄컴',
    'QS': '퀀텀스케이프',
    'RBLX': '로블록스',
    'RDDT': '레딧',
    'REGN': '리제네론',
    'RHLD': '리졸루트 홀딩스',
    'RIGL': '라이젤 파마슈티컬스',
    'RIO': '리오 틴토',
    'RIVN': '리비안',
    'RL': '랄프 로렌',
    'ROK': '록웰 오토메이션',
    'ROKU': '로쿠',
    'ROST': '로스스토어스',
    'RTX': '알티엑스',
    'S': '센티넬원',
    'SBUX': '스타벅스',
    'SCCO': '서던 코퍼',
    'SCHW': '찰스 슈왑',
    'SEDG': '솔라엣지',
    'SHOP': '쇼피파이',
    'SLB': '에스엘비',
    'SLP': '시뮬레이션스 플러스',
    'SMCI': '슈퍼마이크로컴퓨터',
    'SMR': '뉴스케일 파워',
    'SMTI': '사나라 메드테크',
    'SNDK': '샌디스크',
    'SNOW': '스노우플레이크',
    'SO': '서던 컴퍼니',
    'SPG': '사이먼 프로퍼티 그룹',
    'SPGI': '에스앤피 글로벌',
    'SQ': '블록',
    'SQM': '에스큐엠',
    'STLD': '스틸 다이내믹스',
    'STX': '시게이트',
    'SYK': '스트라이커',
    'T': '에이티앤티',
    'TEAM': '아틀라시안',
    'TEL': '티이 커넥티비티',
    'TER': '테라다인',
    'TGT': '타깃',
    'TJX': '티제이엑스',
    'TLS': '텔로스',
    'TM': '토요타',
    'TMO': '써모 피셔 사이언티픽',
    'TMUS': '티모바일 유에스',
    'TRV': '트래블러스',
    'TSEM': '타워 세미컨덕터',
    'TSLA': '테슬라',
    'TSM': '티에스엠씨',
    'TT': '트레인 테크놀로지스',
    'TTWO': '테이크투 인터랙티브',
    'TXN': '텍사스 인스트루먼트',
    'UAL': '유나이티드항공',
    'UBER': '우버',
    'UMC': '유나이티드 마이크로일렉트로닉스',
    'UNH': '유나이티드헬스 그룹',
    'UNP': '유니언 퍼시픽',
    'UPS': '유피에스',
    'URI': '유나이티드 렌털스',
    'USB': '유에스 뱅코프',
    'UUUU': '에너지 퓨얼스',
    'V': '비자',
    'VLO': '발레로 에너지',
    'VMC': '벌컨 머티리얼즈',
    'VMD': '비메드 헬스케어',
    'VRT': '버티브',
    'VST': '비스트라',
    'VTRS': '비아트리스',
    'VZ': '버라이즌',
    'WAT': '워터스',
    'WBD': '워너브러더스 디스커버리',
    'WDAY': '워크데이',
    'WDC': '웨스턴디지털',
    'WFC': '웰스파고',
    'WMT': '월마트',
    'WSM': '윌리엄스소노마',
    'WST': '웨스트 파마슈티컬',
    'XOM': '엑슨모빌',
    'ZBRA': '지브라 테크놀로지스',
    'ZS': '지스케일러',
}

_NON_COMPANY_NAME_TERMS = (
    " etf", " fund", " trust", " shares", " index", " futures", " future", " bond",
    " treasury", " yield", "spdr", "ishares", "vanguard", "invesco", "ark ",
    "kodex", "tiger", "kospi", "kosdaq", "s&p", "nasdaq", "gold", "silver",
    "oil", "copper", "bitcoin", "ethereum",
)


def contains_hangul(value: object) -> bool:
    return bool(re.search(r"[가-힣]", str(value or "")))


def _kr_code(value: object) -> str:
    match = re.search(r"(\d{6})", str(value or "").strip().upper())
    return match.group(1) if match else ""


def _is_kr_ticker(ticker: object, market: str | None = None) -> bool:
    market_key = str(market or "").strip().upper()
    if market_key == "KR":
        return True
    return bool(re.fullmatch(r"\d{6}(?:\.(?:KS|KQ))?", str(ticker or "").strip().upper()))


def _company_name_symbol(ticker: object) -> str:
    text = str(ticker or "").strip().upper().replace(".", "-")
    if not text or text.startswith("^") or "=" in text:
        return ""
    match = re.search(r"[A-Z][A-Z0-9-]{0,7}", text)
    return match.group(0) if match else ""


def _is_non_company_name(value: object) -> bool:
    text = str(value or "").strip().lower()
    return any(term in text for term in _NON_COMPANY_NAME_TERMS)


def _is_generic_ticker_company_name(name: object, ticker: object) -> bool:
    clean_name = str(name or "").strip()
    if not clean_name.endswith("기업"):
        return False
    prefix = clean_name.removesuffix("기업").strip().upper()
    symbol = _company_name_symbol(ticker)
    upper_ticker = str(ticker or "").strip().upper()
    base_symbol = upper_ticker.split(".", 1)[0]
    return bool(symbol and prefix in {symbol, upper_ticker, base_symbol})


def _display_override(ticker: object, market: str | None = None) -> str | None:
    if _is_kr_ticker(ticker, market):
        code = _kr_code(ticker)
        if code:
            return KR_COMPANY_NAMES.get(code) or DISPLAY_OVERRIDES.get(code)
    symbol = _company_name_symbol(ticker)
    if not symbol:
        return None
    base_symbol = symbol.split(".", 1)[0]
    return DISPLAY_OVERRIDES.get(symbol) or DISPLAY_OVERRIDES.get(base_symbol) or US_COMPANY_NAMES_KO.get(symbol)


def localized_company_name(ticker: object, name: object, market: str | None = None) -> str:
    clean_name = str(name or "").strip()
    symbol = _company_name_symbol(ticker)
    override = _display_override(ticker, market)

    if _is_generic_ticker_company_name(clean_name, ticker):
        return override or symbol or str(ticker or "").strip()
    if contains_hangul(clean_name):
        return clean_name
    if override and not _is_non_company_name(clean_name):
        return override
    if not clean_name:
        return override or str(ticker or "").strip()
    return clean_name


def localize_company_name_fields(record: dict[str, Any]) -> dict[str, Any]:
    ticker = record.get("Ticker") or record.get("ticker")
    market = record.get("Market") or record.get("market")
    if not ticker:
        return record
    if "Name" in record and record.get("Name") is not None:
        record["Name"] = localized_company_name(ticker, record.get("Name"), market)
    if "name" in record and record.get("name") is not None:
        record["name"] = localized_company_name(ticker, record.get("name"), market)
    return record


def apply_localized_names(value: Any) -> Any:
    if isinstance(value, list):
        return [apply_localized_names(item) for item in value]
    if isinstance(value, tuple):
        return tuple(apply_localized_names(item) for item in value)
    if isinstance(value, Mapping):
        localized = {key: apply_localized_names(item) for key, item in value.items()}
        return localize_company_name_fields(localized)
    return value
