# ── Path bootstrap ─────────────────────────────────────────────────────────
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)
_KEY_JSON = os.path.join(_ROOT, 'key.json')
# ───────────────────────────────────────────────────────────────────────────
"""
00_schema_writer.py  ─  Database Schema Documentation
======================================================
Creates / updates a 'Schema' sheet in QuantBridge_Demo_Workbook.
Documents every sheet's column names, data types, and update frequency.
Run this once after any structural change to the pipeline.
"""

import gspread
from sheets_client import get_spreadsheet
from datetime import datetime

# ── Google Sheets connection ──────────────────────────────────────────────────
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
spreadsheet = get_spreadsheet()

# ══════════════════════════════════════════════════════════════════════════════
# MASTER SCHEMA DEFINITION
# ══════════════════════════════════════════════════════════════════════════════

SCHEMA = [
    # ── Header ──────────────────────────────────────────────────────────────
    ["QuantBridge_Demo_Workbook  —  Schema Reference", "", "", "", ""],
    [f"Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", "", "", "", ""],
    ["", "", "", "", ""],
    ["Sheet", "Column", "Type", "Format / Unit", "Description"],

    # ── Cache Layer ──────────────────────────────────────────────────────────
    ["=== CACHE LAYER ===", "", "", "", "Updated automatically by CacheManager"],
    ["Company_Master", "Ticker",          "str",   "e.g. AAPL / 005930.KS",   "Stock ticker symbol"],
    ["Company_Master", "Name",            "str",   "text",                    "Company name"],
    ["Company_Master", "Market",          "str",   "US | KR",                 "Market identifier"],
    ["Company_Master", "Sector",          "str",   "text",                    "GICS sector"],
    ["Company_Master", "MarketCap",       "float", "raw number (USD or KRW)", "Market capitalisation"],
    ["Company_Master", "ROIC",            "float", "decimal (0.1234)",        "Return on invested capital"],
    ["Company_Master", "RevGrowth",       "float", "decimal (0.15 = 15%)",    "Revenue growth YoY"],
    ["Company_Master", "PEG",             "float", "decimal",                 "Price/Earnings-to-Growth"],
    ["Company_Master", "GrossMargin",     "float", "decimal (0.1234)",        "Gross profit margin"],
    ["Company_Master", "FCF_Margin",      "float", "decimal (0.1234)",        "Free cash flow margin"],
    ["Company_Master", "Debt_EBITDA",     "float", "decimal",                 "Net debt / EBITDA ratio"],
    ["Company_Master", "Next_Earnings",   "str",   "YYYY-MM-DD",              "Next earnings date"],
    ["Company_Master", "Last_Fin_Update", "str",   "YYYY-MM-DDTHH:MM:SS",    "Last fundamentals refresh"],
    ["Company_Master", "Last_Mkt_Update", "str",   "YYYY-MM-DDTHH:MM:SS",    "Last market data refresh"],
    ["", "", "", "", ""],
    ["Earnings_Calendar", "Ticker",        "str",  "e.g. AAPL",              "Stock ticker symbol"],
    ["Earnings_Calendar", "Next_Earnings", "str",  "YYYY-MM-DD",             "Next scheduled earnings date"],
    ["Earnings_Calendar", "Last_Updated",  "str",  "YYYY-MM-DD",             "When this row was last fetched"],
    ["", "", "", "", ""],

    # ── US Pipeline ──────────────────────────────────────────────────────────
    ["=== US PIPELINE (USD) ===", "", "", "", "Generated by 01 → 02 → 03 → 04 → 05 → 06"],
    ["US_Universe",          "Ticker",         "str",   "e.g. AAPL",              "US stock ticker"],
    ["US_Universe",          "Name",           "str",   "text",                   "Company name"],
    ["US_Universe",          "Market",         "str",   "US",                     "Always 'US'"],
    ["US_Universe",          "Sector",         "str",   "text",                   "GICS sector"],
    ["US_Universe",          "MarketCap",      "float", "raw USD",                "Market cap in USD"],
    ["US_Universe",          "PER",            "float", "2 decimal places",       "Price-to-Earnings (trailing)"],
    ["US_Universe",          "PBR",            "float", "2 decimal places",       "Price-to-Book ratio"],
    ["US_Universe",          "ROE",            "float", "decimal (0.1234)",       "Return on equity"],
    ["US_Universe",          "Revenue",        "float", "raw USD",                "Annual revenue"],
    ["US_Universe",          "RevenueGrowth",  "float", "decimal (0.15 = 15%)",   "Revenue growth YoY"],
    ["US_Universe",          "OperatingMargin","float", "decimal (0.1234)",       "Operating profit margin"],
    ["US_Universe",          "GrossMargin",    "float", "decimal (0.1234)",       "Gross margin"],
    ["US_Universe",          "DebtToEquity",   "float", "percentage scale (50=50%)","Debt-to-equity ratio"],
    ["US_Universe",          "Last_Updated",   "str",   "YYYY-MM-DD",             "Date row was written"],
    ["", "", "", "", ""],
    ["US_Scored_Stocks",   "Rank",           "int",   "1, 2, 3...",             "Rank by Total_Score"],
    ["US_Scored_Stocks",   "Ticker",         "str",   "e.g. AAPL",              "US stock ticker"],
    ["US_Scored_Stocks",   "Name",           "str",   "text",                   "Company name"],
    ["US_Scored_Stocks",   "Market",         "str",   "US",                     "Always 'US'"],
    ["US_Scored_Stocks",   "Sector",         "str",   "text",                   "GICS sector"],
    ["US_Scored_Stocks",   "MarketCap",      "float", "raw USD",                "Market cap"],
    ["US_Scored_Stocks",   "Value_Score",    "float", "0.0000 ~ 0.4000",        "Value factor score (40% weight)"],
    ["US_Scored_Stocks",   "Quality_Score",  "float", "0.0000 ~ 0.3000",        "Quality factor score (30% weight)"],
    ["US_Scored_Stocks",   "Momentum_Score", "float", "0.0000 ~ 0.3000",        "Momentum factor score (30% weight)"],
    ["US_Scored_Stocks",   "Total_Score",    "float", "0.0000 ~ 1.0000",        "Sum of V+Q+M scores"],
    ["US_Scored_Stocks",   "ROIC",           "float", "decimal (0.1234)",       "Return on invested capital"],
    ["US_Scored_Stocks",   "RevGrowth",      "float", "decimal (0.15 = 15%)",   "Revenue growth"],
    ["US_Scored_Stocks",   "GrossMargin",    "float", "decimal (0.1234)",       "Gross margin"],
    ["US_Scored_Stocks",   "FCF_Margin",     "float", "decimal (0.1234)",       "FCF margin"],
    ["US_Scored_Stocks",   "PEG",            "float", "decimal",                "PEG ratio"],
    ["US_Scored_Stocks",   "Last_Updated",   "str",   "YYYY-MM-DD",             "Date row was written"],
    ["", "", "", "", ""],
    ["US_Final_Portfolio", "Rank",           "int",   "1, 2, 3...",             "Rank by Weight"],
    ["US_Final_Portfolio", "Ticker",         "str",   "e.g. AAPL",              "US stock ticker"],
    ["US_Final_Portfolio", "Name",           "str",   "text",                   "Company name"],
    ["US_Final_Portfolio", "Market",         "str",   "US",                     "Always 'US'"],
    ["US_Final_Portfolio", "Sector",         "str",   "text",                   "GICS sector"],
    ["US_Final_Portfolio", "MarketCap",      "float", "raw USD",                "Market cap"],
    ["US_Final_Portfolio", "Weight(%)",      "float", "percentage (5.23)",      "Portfolio weight %"],
    ["US_Final_Portfolio", "Total_Score",    "float", "0.0000 ~ 1.0000",        "Factor + ML combined score"],
    ["US_Final_Portfolio", "ROIC",           "float", "decimal (0.1234)",       "Return on invested capital"],
    ["US_Final_Portfolio", "RevGrowth",      "float", "decimal (0.15 = 15%)",   "Revenue growth"],
    ["US_Final_Portfolio", "GrossMargin",    "float", "decimal (0.1234)",       "Gross margin"],
    ["US_Final_Portfolio", "Expected_Return","float", "decimal (0.1234)",       "Historical annualised return"],
    ["US_Final_Portfolio", "Last_Updated",   "str",   "YYYY-MM-DD",             "Date row was written"],
    ["", "", "", "", ""],

    # ── KR Pipeline ──────────────────────────────────────────────────────────
    ["=== KR PIPELINE (KRW, no USD mix) ===", "", "", "", "Generated by 01 → 03"],
    ["KR_Universe",    "Ticker",         "str",  "e.g. 005930.KS",        "KR stock ticker"],
    ["KR_Universe",    "Name",           "str",  "text",                  "Company name (Korean)"],
    ["KR_Universe",    "Market",         "str",  "KR",                    "Always 'KR'"],
    ["KR_Universe",    "Sector",         "str",  "text",                  "GICS sector"],
    ["KR_Universe",    "MarketCap",      "float","raw KRW",               "Market cap in KRW"],
    ["KR_Universe",    "PER",            "float","2 decimal places",      "Price-to-Earnings"],
    ["KR_Universe",    "PBR",            "float","2 decimal places",      "Price-to-Book"],
    ["KR_Universe",    "ROE",            "float","decimal (0.1234)",      "Return on equity"],
    ["KR_Universe",    "Revenue",        "float","raw KRW",               "Annual revenue"],
    ["KR_Universe",    "RevenueGrowth",  "float","decimal (0.15 = 15%)",  "Revenue growth YoY"],
    ["KR_Universe",    "OperatingMargin","float","decimal (0.1234)",      "Operating margin"],
    ["KR_Universe",    "GrossMargin",    "float","decimal (0.1234)",      "Gross margin"],
    ["KR_Universe",    "DebtToEquity",   "float","percentage scale",      "Debt-to-equity"],
    ["KR_Universe",    "Last_Updated",   "str",  "YYYY-MM-DD",            "Date row was written"],
    ["", "", "", "", ""],
    ["KR_Scored_Stocks",   "Rank",           "int",  "1, 2, 3...",            "Rank by Total_Score"],
    ["KR_Scored_Stocks",   "Ticker",         "str",  "e.g. 005930.KS",        "KR stock ticker"],
    ["KR_Scored_Stocks",   "Name",           "str",  "text",                  "Company name"],
    ["KR_Scored_Stocks",   "Market",         "str",  "KR",                    "Always 'KR'"],
    ["KR_Scored_Stocks",   "Sector",         "str",  "text",                  "GICS sector"],
    ["KR_Scored_Stocks",   "MarketCap",      "float","raw KRW",               "Market cap"],
    ["KR_Scored_Stocks",   "Value_Score",    "float","0.0000 ~ 0.4000",       "Value factor score (40% weight)"],
    ["KR_Scored_Stocks",   "Quality_Score",  "float","0.0000 ~ 0.3500",       "Quality factor score (35% weight)"],
    ["KR_Scored_Stocks",   "Momentum_Score", "float","0.0000 ~ 0.2500",       "Momentum factor score (25% weight)"],
    ["KR_Scored_Stocks",   "Total_Score",    "float","0.0000 ~ 1.0000",       "Sum of V+Q+M scores"],
    ["KR_Scored_Stocks",   "ROIC",           "float","decimal (0.1234)",      "Return on invested capital"],
    ["KR_Scored_Stocks",   "RevGrowth",      "float","decimal (0.15 = 15%)", "Revenue growth"],
    ["KR_Scored_Stocks",   "GrossMargin",    "float","decimal (0.1234)",      "Gross margin"],
    ["KR_Scored_Stocks",   "FCF_Margin",     "float","decimal (0.1234)",      "FCF margin"],
    ["KR_Scored_Stocks",   "PEG",            "float","decimal",               "PEG ratio"],
    ["KR_Scored_Stocks",   "Last_Updated",   "str",  "YYYY-MM-DD",            "Date row was written"],
    ["", "", "", "", ""],
    ["KR_Final_Portfolio", "Rank",           "int",  "1, 2, 3...",            "Rank by Weight"],
    ["KR_Final_Portfolio", "Ticker",         "str",  "e.g. 005930.KS",        "KR stock ticker"],
    ["KR_Final_Portfolio", "Name",           "str",  "text",                  "Company name"],
    ["KR_Final_Portfolio", "Market",         "str",  "KR",                    "Always 'KR'"],
    ["KR_Final_Portfolio", "Sector",         "str",  "text",                  "GICS sector"],
    ["KR_Final_Portfolio", "MarketCap",      "float","raw KRW",               "Market cap"],
    ["KR_Final_Portfolio", "Weight(%)",      "float","percentage (5.23)",     "Portfolio weight %"],
    ["KR_Final_Portfolio", "Total_Score",    "float","0.0000 ~ 1.0000",       "Factor score"],
    ["KR_Final_Portfolio", "ROIC",           "float","decimal (0.1234)",      "Return on invested capital"],
    ["KR_Final_Portfolio", "RevGrowth",      "float","decimal (0.15 = 15%)",  "Revenue growth"],
    ["KR_Final_Portfolio", "GrossMargin",    "float","decimal (0.1234)",      "Gross margin"],
    ["KR_Final_Portfolio", "Expected_Return","float","decimal (0.1234)",      "Historical annualised return"],
    ["KR_Final_Portfolio", "Last_Updated",   "str",  "YYYY-MM-DD",            "Date row was written"],
    ["", "", "", "", ""],

    # ── SmallCap Pipeline ────────────────────────────────────────────────────
    ["=== SMALLCAP PIPELINE ===", "", "", "", "Generated by 07_smallcap_scanner.py"],
    ["US_SmallCap_Gems",  "Rank",           "int",  "1 ~ 20",                 "Rank by Total_Score"],
    ["US_SmallCap_Gems",  "Ticker",         "str",  "e.g. SMCI",              "US small-cap ticker"],
    ["US_SmallCap_Gems",  "Name",           "str",  "text",                   "Company name"],
    ["US_SmallCap_Gems",  "Market",         "str",  "US",                     "Always 'US'"],
    ["US_SmallCap_Gems",  "MarketCap",      "float","raw USD ($100M ~ $1B)",  "Market cap"],
    ["US_SmallCap_Gems",  "ROIC",           "float","decimal (0.1234)",       "Return on invested capital"],
    ["US_SmallCap_Gems",  "RevGrowth",      "float","decimal (0.15 = 15%)",   "Revenue growth"],
    ["US_SmallCap_Gems",  "PEG",            "float","decimal",                "PEG ratio"],
    ["US_SmallCap_Gems",  "GrossMargin",    "float","decimal (0.1234)",       "Gross margin"],
    ["US_SmallCap_Gems",  "FCF_Margin",     "float","decimal (0.1234)",       "FCF margin"],
    ["US_SmallCap_Gems",  "Debt_EBITDA",    "float","decimal (ratio)",        "Net debt / EBITDA"],
    ["US_SmallCap_Gems",  "Volume_Surge",   "float","decimal (3.0 = 3x avg)", "Volume vs 3mo average"],
    ["US_SmallCap_Gems",  "SmallCap_Bonus", "float","0 ~ 15 pts",             "Bonus for smaller market cap"],
    ["US_SmallCap_Gems",  "Data_Confidence","float","0.75 ~ 1.00",            "Score multiplier from metric coverage"],
    ["US_SmallCap_Gems",  "Total_Score",    "float","0 ~ 115 pts",            "Total small-cap score"],
    ["US_SmallCap_Gems",  "Last_Updated",   "str",  "YYYY-MM-DD",             "Date row was written"],
    ["", "", "", "", ""],
    ["KR_SmallCap_Gems",  "Rank",           "int",  "1 ~ 20",                 "Rank by Total_Score"],
    ["KR_SmallCap_Gems",  "Ticker",         "str",  "e.g. 123456.KQ",         "KR small-cap ticker"],
    ["KR_SmallCap_Gems",  "Name",           "str",  "text",                   "Company name (Korean)"],
    ["KR_SmallCap_Gems",  "Market",         "str",  "KR",                     "Always 'KR'"],
    ["KR_SmallCap_Gems",  "MarketCap",      "float","raw KRW (1000억 ~ 10조)","Market cap in KRW"],
    ["KR_SmallCap_Gems",  "ROIC",           "float","decimal (0.1234)",       "Return on invested capital"],
    ["KR_SmallCap_Gems",  "RevGrowth",      "float","decimal (0.15 = 15%)",   "Revenue growth"],
    ["KR_SmallCap_Gems",  "PEG",            "float","decimal",                "PEG ratio"],
    ["KR_SmallCap_Gems",  "GrossMargin",    "float","decimal (0.1234)",       "Gross margin"],
    ["KR_SmallCap_Gems",  "FCF_Margin",     "float","decimal (0.1234)",       "FCF margin"],
    ["KR_SmallCap_Gems",  "Debt_EBITDA",    "float","decimal (ratio)",        "Net debt / EBITDA"],
    ["KR_SmallCap_Gems",  "Volume_Surge",   "float","decimal (3.0 = 3x avg)", "Volume vs 3mo average"],
    ["KR_SmallCap_Gems",  "SmallCap_Bonus", "float","0 ~ 15 pts",             "Bonus for smaller market cap"],
    ["KR_SmallCap_Gems",  "Data_Confidence","float","0.75 ~ 1.00",            "Score multiplier from metric coverage"],
    ["KR_SmallCap_Gems",  "Total_Score",    "float","0 ~ 115 pts",            "Total small-cap score"],
    ["KR_SmallCap_Gems",  "Last_Updated",   "str",  "YYYY-MM-DD",             "Date row was written"],
    ["", "", "", "", ""],

    # ── Number Format Rules ──────────────────────────────────────────────────
    ["=== NUMBER FORMAT RULES ===", "", "", "", ""],
    ["Rule", "Column Type",     "Format",          "Example",     "Note"],
    ["1",    "Ratios / Margins","4 decimal places","0.1234",      "ROE, ROIC, GrossMargin, FCF_Margin"],
    ["2",    "Percentages",     "decimal not %",   "0.15",        "0.15 means 15% — never store as 15"],
    ["3",    "MarketCap",       "raw number",      "1500000000",  "Not formatted string like '$1.5B'"],
    ["4",    "Dates",           "YYYY-MM-DD",       "2026-03-26",  "ISO 8601 format"],
    ["5",    "Timestamps",      "ISO 8601",         "2026-03-26T22:00:00", "For cache Last_Updated fields"],
    ["6",    "PER / PBR",       "2 decimal places","15.23",       "Less precision needed"],
    ["7",    "Weight(%)",       "percentage",       "5.23",        "Stored as actual % not decimal"],
]

# ══════════════════════════════════════════════════════════════════════════════
# Write to Google Sheets
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 65)
print("  SCHEMA WRITER  —  QuantBridge_Demo_Workbook")
print("=" * 65)

try:
    schema_sheet = spreadsheet.worksheet("Schema")
    schema_sheet.clear()
    print("  Existing 'Schema' sheet found — clearing...")
except gspread.exceptions.WorksheetNotFound:
    schema_sheet = spreadsheet.add_worksheet(title="Schema", rows=200, cols=5)
    print("  Created new 'Schema' sheet")

schema_sheet.update(SCHEMA)
schema_sheet.freeze(rows=4, cols=1)

print(f"\n✅ Schema written: {len(SCHEMA)} rows")
print(f"   Sheets documented: US_Universe, KR_Universe, US_Scored_Stocks,")
print(f"   KR_Scored_Stocks, US_Final_Portfolio, KR_Final_Portfolio,")
print(f"   US_SmallCap_Gems, KR_SmallCap_Gems, Company_Master, Earnings_Calendar")
print(f"   → Open 'Schema' tab in QuantBridge_Demo_Workbook to view")
