#!/usr/bin/env bash
set -euo pipefail

API_URL="http://127.0.0.1:8000"
OPENAPI_GENERATOR_IMAGE="${OPENAPI_GENERATOR_IMAGE:-openapitools/openapi-generator-cli:v7.13.0}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-url)
      API_URL="${2:?--api-url requires a value}"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: scripts/regen-mobile-clients.sh [--api-url http://127.0.0.1:8000]

Regenerates tracked mobile OpenAPI artifacts from the QuantBridge FastAPI server.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

API_URL="${API_URL%/}"
OPENAPI_JSON="api/openapi.json"
SWIFT_OUT="Stock Analysis/Stock Analysis/Generated"
KOTLIN_OUT="android/app/src/main/java/com/qubit/quantbridge/generated"
README_TEXT="이 폴더는 scripts/regen-mobile-clients.sh로 생성된 자동 산출물입니다. 직접 편집 금지."

echo "Fetching ${API_URL}/openapi.json"
curl --fail --silent --show-error --location "${API_URL}/openapi.json" --output "$OPENAPI_JSON"
python3 - <<'PY'
import json
from pathlib import Path

spec = json.loads(Path("api/openapi.json").read_text())
schemas = spec.get("components", {}).get("schemas", {})
missing = []

def has_ref(value):
    if isinstance(value, dict):
        return "$ref" in value or any(has_ref(child) for child in value.values())
    if isinstance(value, list):
        return any(has_ref(child) for child in value)
    return False

for path, methods in spec.get("paths", {}).items():
    for method, operation in methods.items():
        if method.lower() not in {"get", "post", "put", "patch", "delete"}:
            continue
        schema = (
            operation.get("responses", {})
            .get("200", {})
            .get("content", {})
            .get("application/json", {})
            .get("schema")
        )
        if not has_ref(schema):
            missing.append(f"{method.upper()} {path}")

if len(schemas) < 60 or missing:
    raise SystemExit(
        "OpenAPI spec is not ready for mobile codegen: "
        f"{len(schemas)} schemas, missing typed 200 responses={missing}"
    )
PY

rm -rf "$SWIFT_OUT" "$KOTLIN_OUT"
mkdir -p "$SWIFT_OUT" "$KOTLIN_OUT"

run_generator() {
  docker run --rm \
    --user "$(id -u):$(id -g)" \
    --volume "$REPO_ROOT:/local" \
    --workdir /local \
    "$OPENAPI_GENERATOR_IMAGE" "$@"
}

normalize_generated_text() {
  find "$SWIFT_OUT" "$KOTLIN_OUT" -type f \( -name '*.swift' -o -name '*.kt' -o -name '*.md' \) -print0 | \
    xargs -0 perl -0pi -e 's/[ \t]+$//mg; s/\n+\z/\n/s;'
}

echo "Generating Swift models"
run_generator generate \
  -i /local/api/openapi.json \
  -g swift5 \
  -o "/local/${SWIFT_OUT}" \
  --model-name-prefix QB \
  --additional-properties=projectName=QuantBridgeAPI,responseAs=AsyncAwait \
  --model-name-mappings ValidationError=APIValidationError \
  --global-property models,supportingFiles,modelDocs=false,modelTests=false,apis=false
rm -f "$SWIFT_OUT/Package.swift" "$SWIFT_OUT/.gitignore"
rm -rf "$SWIFT_OUT/.openapi-generator"
rm -f \
  "$SWIFT_OUT/.openapi-generator-ignore" \
  "$SWIFT_OUT/.swiftformat" \
  "$SWIFT_OUT/Cartfile" \
  "$SWIFT_OUT/QuantBridgeAPI.podspec" \
  "$SWIFT_OUT/git_push.sh" \
  "$SWIFT_OUT/project.yml"
if [[ -f "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Models.swift" ]]; then
  mv "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Models.swift" \
    "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/OpenAPIModelsSupport.swift"
fi
if [[ -f "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Configuration.swift" ]]; then
  perl -0pi -e 's/\bConfiguration\b/OpenAPIConfiguration/g' \
    "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Configuration.swift" \
    "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Extensions.swift"
  mv "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/Configuration.swift" \
    "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/OpenAPIConfiguration.swift"
fi
cat > "$SWIFT_OUT/QuantBridgeAPI/Classes/OpenAPIs/AnyCodable.swift" <<'EOF'
//
// AnyCodable.swift
//
// Generated by scripts/regen-mobile-clients.sh
//

import Foundation

public struct AnyCodable: Codable, Hashable {
    public let value: AnyHashable?

    public init(_ value: Any?) {
        self.value = AnyCodable.hashableValue(value)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            value = nil
        } else if let bool = try? container.decode(Bool.self) {
            value = bool
        } else if let int = try? container.decode(Int.self) {
            value = int
        } else if let double = try? container.decode(Double.self) {
            value = double
        } else if let string = try? container.decode(String.self) {
            value = string
        } else {
            value = nil
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch value {
        case .none:
            try container.encodeNil()
        case let bool as Bool:
            try container.encode(bool)
        case let int as Int:
            try container.encode(int)
        case let double as Double:
            try container.encode(double)
        case let string as String:
            try container.encode(string)
        default:
            try container.encodeNil()
        }
    }

    private static func hashableValue(_ value: Any?) -> AnyHashable? {
        switch value {
        case let value as AnyHashable:
            return value
        default:
            return nil
        }
    }
}
EOF

echo "Generating Kotlin models"
run_generator generate \
  -i /local/api/openapi.json \
  -g kotlin \
  -o "/local/${KOTLIN_OUT}" \
  --model-name-prefix QB \
  --additional-properties=library=jvm-retrofit2,serializationLibrary=kotlinx_serialization,useCoroutines=true,packageName=com.qubit.quantbridge.generated \
  --model-name-mappings ValidationError=APIValidationError \
  --global-property models,modelDocs=false,modelTests=false,supportingFiles=false,apis=false
find "$KOTLIN_OUT/src/main/kotlin" -type f -name '*.kt' -print0 | \
  xargs -0 perl -0pi \
    -e 's/kotlin\.Any/kotlinx.serialization.json.JsonElement/g;' \
    -e 's/java\.math\.BigDecimal/kotlin.Double/g;' \
    -e 's/kotlin\.Double\("0"\)/0.0/g;'
rm -rf "$KOTLIN_OUT/.openapi-generator"

printf '%s\n' "$README_TEXT" > "$SWIFT_OUT/README.md"
printf '%s\n' "$README_TEXT" > "$KOTLIN_OUT/README.md"
normalize_generated_text

echo "Regenerated mobile clients from ${API_URL}"
